language: scala
dist: xenial

jobs:
  include:
    - name: Tests 2.12
      script:
        - ./millw all {json[2.12.11],xml[2.12.11],csv[2.12.11]}.__.test
    - name: Tests 2.13
      script:
        - ./millw all {json[2.13.3],xml[2.13.3],csv[2.13.3]}.__.test
    - name: Documentation
      scala: 2.12.11
      script:
        - ./millw documentation.mdoc

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.mill/download

jdk:
  - openjdk11

branches:
  only:
  - master
