name: Publish Website

on:
  release:
    types:
      - published

jobs:
  publish:
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: olafurpg/setup-scala@v10
      - uses: actions/setup-ruby@v1
      - name: Install nanoc
        run: |
          gem install nanoc kramdown-parser-gfm rouge
      - name: "Compile documentation"
        run: "sbt ++2.13.6 documentation/mdoc"
      - name: "Build site"
        run: "sbt makeSite"
      - name: "Publish site"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site
