name: Publish Website

on:
  release:
    types:
      - published

jobs:
  publish:
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Install nanoc
        run: |
          gem install nanoc kramdown-parser-gfm rouge
      - name: "Compile documentation"
        run: "sbt documentation/mdoc"
      - name: "Build site"
        run: "sbt makeSite"
      - name: "Publish site"
        run: "sbt ghpagesPushSite"
